### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by Wisest-Maiar** [dobin/avred-server#1]
I've got python3 pip and the requirements installed and ready on a windows vm. Does it require any args? 
![image](https://github.com/dobin/avred-server/assets/86758465/67f4bbaf-9f85-4dc9-a7cd-832a02aa8002)
Do I need to modify the config? It seems like it should run with default and listen on all interface.

**Comment by Wisest-Maiar** [comment]
nvm I got it to work. I was using python3 instead of python2

**Comment by dobin** [comment]
It is for python3 :-) I've installed it from the python windows installer (3.9.5). Glad its working tho. 

For future reference: 

![image](https://github.com/dobin/avred-server/assets/3250886/5ef0c6f7-769d-433e-bb7c-7709c57dab35)
